//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace MeyawoPortfolio.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class TblEducation
    {
        public int EgıtımID { get; set; }
        public string IlkOkul { get; set; }
        public string Lise { get; set; }
        public string Universite { get; set; }
    }
}
